### PR TITLE
SF Pro ➡️ SF Pro Display

### PR DESCRIPTION
**Pull request by Monochromish**

### CODE REVIEW

**Comment by yazninja** [comment]
doesnt work this way, i use webfonts and base64

**Comment by Monochromish** [comment]
I've tested it locally and works for me at least, Could you test on your side.
If it does not work this way, then I'll convert it into base64.

**Comment by yazninja** [comment]
it does work but this is heavy

**Comment by Monochromish** [comment]
Okay, I'll convert it to base64

**Comment by Monochromish** [comment]
@yazninja there, it's sf pro display in base64 now. Tested and works atleast on my side.

**Comment by yazninja** [comment]
yep nice, merging it, thanks!

**Pull request merged**
